version: 2.1
executors:
  node-executor:
    docker:
      - image: circleci/node:10
        user: node
commands:
  gatsby-build:
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-v2-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Install Wrangler
          command: npm install @cloudflare/wrangler@1.6.0
      - save_cache:
          key: npm-cache-v2-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: npm run build
workflows:
  version: 2
  build-deploy:
    jobs:
      - release:
          filters:
            branches:
              only:
                - master
jobs:
  release:
    executor: node-executor
    working_directory: ~/repo
    steps:
      - gatsby-build
      - run:
          name: Deploy
          command: USER=node ./node_modules/@cloudflare/wrangler/run-wrangler.js publish
